services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: vyaaparai-backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_GOOGLE_CLIENT_ID: 1021555363283-o1l7l2ji5v8pqj2ng346abbjfvcjg1vo.apps.googleusercontent.com
    container_name: vyaaparai-frontend
    depends_on:
      - backend
    ports:
      - "80:80"
    restart: unless-stopped
