import { Bot } from "lucide-react";
import Card from "../common/Card";

export default function AIInsight() {
  return (
    <Card>
      <div className="flex items-center gap-3">

        <div className="rounded-xl bg-primary/10 p-3">
          <Bot className="h-6 w-6 text-primary" />
        </div>

        <div>
          <h2 className="font-bold text-text-primary">
            AI Business Insight
          </h2>

          <p className="text-sm text-text-secondary">
            Generated by VyaparAI
          </p>
        </div>

      </div>

      <div className="mt-5 rounded-xl bg-primary/5 p-4">

        <p className="text-sm text-text-primary">
          📈 Revenue increased by <b>12%</b> this month.
        </p>

        <p className="mt-3 text-sm text-text-primary">
          ⚠️ Cooking Oil stock may finish within 3 days.
        </p>

        <p className="mt-3 text-sm text-text-primary">
          💡 Offer a discount on Tea Powder to boost sales.
        </p>

      </div>
    </Card>
  );
}
